### ISSUE TITLE
[FEATURE]: Please, add title via checking progress bar and fix-check on tasklist

### ISSUE THREAD

**Issue by FlewToL** [Falcion/Patternunote#1]
### Contact details

github

### What the essence of your feature request

- Add titltes to progress bars (either from .MD parsing data or filename);
- Add tasklist checks for incorrect formats (`-[]`, `-[[]` and etc.);

### On what OS you want to maintain your request.

Not important

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
Implemented in new version, see last commit: [fa7f8ac](https://github.com/Falcion/Patternunote/commit/fa7f8ac087e209f704c77f56875e3df1f618d319)
